apiVersion: v1
description: Bookinfo Ratings Service Helm Chart
name: bookinfo-ratings
version: 1.0.0
appVersion: 1.0.0
home: https://bookinfo.dev.opsta.net/student114/ratings
maintainers:
  - name: student114
    email: devop114@mail.kmutt.ac.th
sources:
  - https://github.com/peemkaka/bookinfo-ratings